/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.81
 * Generated at: 2022-07-22 05:40:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.city;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class citydetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/views/inc/asset.jsp", Long.valueOf(1658109870487L));
    _jspx_dependants.put("/WEB-INF/views/inc/citysubmenu.jsp", Long.valueOf(1658384895779L));
    _jspx_dependants.put("/WEB-INF/views/inc/header.jsp", Long.valueOf(1658465825745L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1658109870453L));
    _jspx_dependants.put("jar:file:/C:/Users/rhdqn/class/PlanItShare/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/PlanItShare/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Plan It Share</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\" integrity=\"sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn\" crossorigin=\"anonymous\">\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\" integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.5.1.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/planitshare/asset/css/style.css\" />\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"/planitshare/asset/favicon.ico\">\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/planitshare/asset/css/jquery-ui.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://kit.fontawesome.com/94e7820b34.js\" crossorigin=\"anonymous\"></script>");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("#city-submenu {\r\n");
      out.write("      box-shadow: rgba(0, 0, 0, 0.24) 0px 3px 8px;\r\n");
      out.write("      width: 1400px;\r\n");
      out.write("      height: 50px;\r\n");
      out.write("      display: flex;\r\n");
      out.write("      justify-content: space-around;\r\n");
      out.write("      align-items : center;\r\n");
      out.write("      font-size: 1.2rem;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   h2, h3 {\r\n");
      out.write("      text-align: center;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      margin-top: 120px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #search-box {\r\n");
      out.write("      margin: 50px 0;\r\n");
      out.write("      text-align: center;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #search-box > * {\r\n");
      out.write("      display: inline-block;\r\n");
      out.write("      margin-right: 10px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #search-box select {\r\n");
      out.write("      width: 100px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #search-box input[type=text] {\r\n");
      out.write("      width: 300px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #search-box input[type=button] { \r\n");
      out.write("      width: 80px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .fa-solid {\r\n");
      out.write("         margin-left: 7px;\r\n");
      out.write("   }\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   .fa-solid.fa-heart {\r\n");
      out.write("        color: tomato;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #list {\r\n");
      out.write("   \r\n");
      out.write("         width: 1000px;\r\n");
      out.write("         margin: 0 auto;\r\n");
      out.write("         \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .planlist {\r\n");
      out.write("         float: left;\r\n");
      out.write("         margin: 10px;\r\n");
      out.write("         text-align: center;\r\n");
      out.write("         cursor: pointer;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   .planlist > img {\r\n");
      out.write("         width: 300px;\r\n");
      out.write("         height: 200px;\r\n");
      out.write("         background-size: contain;\r\n");
      out.write("            \r\n");
      out.write("         \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .planlist::after {\r\n");
      out.write("        content: '';\r\n");
      out.write("        display: block;\r\n");
      out.write("        clear: both;\r\n");
      out.write("    }\r\n");
      out.write("   \r\n");
      out.write("   .btn-primary {\r\n");
      out.write("         margin-top: 30px;\r\n");
      out.write("         float: right;\r\n");
      out.write("         margin-right: 50px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .CurrIcon > i{\r\n");
      out.write("         width: 65px;\r\n");
      out.write("         height: 65px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .weather {\r\n");
      out.write("         height: 250px;\r\n");
      out.write("         width: 500px;\r\n");
      out.write("         text-align: center;\r\n");
      out.write("         margin-left: 470px;\r\n");
      out.write("         margin-top: 70px;\r\n");
      out.write("         margin-bottom: 50px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("  \r\n");
      out.write("   .iconinfo {\r\n");
      out.write("\r\n");
      out.write("         width: 250px;\r\n");
      out.write("        height: 250px;\r\n");
      out.write("        float: left;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .iconinfo > div{\r\n");
      out.write("         \r\n");
      out.write("         font-size: 1.5em;\r\n");
      out.write("         margin-top: 5px;\r\n");
      out.write("         text-align: center;\r\n");
      out.write("   \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .info {\r\n");
      out.write("         width: 250px;\r\n");
      out.write("         height: 250px;\r\n");
      out.write("        float: left;\r\n");
      out.write("        \r\n");
      out.write("         \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   .info > div {\r\n");
      out.write("         font-size: 1.2em;\r\n");
      out.write("         text-align: left;\r\n");
      out.write("         margin-top: 15px;\r\n");
      out.write("         padding-left: 20px;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #planhead {\r\n");
      out.write("         \r\n");
      out.write("         text-align: center;\r\n");
      out.write("      margin-bottom: 20px;\r\n");
      out.write("      margin-top: 50px;\r\n");
      out.write("         clear: both;\r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("   #icon {\r\n");
      out.write("         padding-right: 40px;\r\n");
      out.write("   \r\n");
      out.write("   }\r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<header>\r\n");
      out.write("   <div id=\"header-logo\"><a href=\"/planitshare/main.do\"><img src=\"/planitshare/asset/image/logo1.png\" alt=\"logo\"></a></div>  \r\n");
      out.write("   <ul id=\"header-menu\">\r\n");
      out.write("       <li><a href=\"/planitshare/main.do\">홈</a></li>\r\n");
      out.write("       <li><a href=\"/planitshare/city.do\">여행지</a></li>\r\n");
      out.write("       <li><a href=\"/planitshare/plan.do\">여행일정</a></li>\r\n");
      out.write("   </ul>\r\n");
      out.write("   \r\n");
      out.write("   <!-- 로그인 안 했을 때 -->\r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <!-- 로그인 했을 때 -->\r\n");
      out.write("   \r\n");
      out.write("   ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   \r\n");
      out.write("</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   \r\n");
      out.write("   <main>\r\n");
      out.write("      <section>\r\n");
      out.write("         ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<h2>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h2>\r\n");
      out.write("		<div id=\"city-submenu\">\r\n");
      out.write("          <span><a href=\"/planitshare/city.do?cseq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">홈</a></span>\r\n");
      out.write("          <span><a href=\"/planitshare/city/lodge.do?cseq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">숙소</a></span>\r\n");
      out.write("          <span><a href=\"/planitshare/city/tour.do?cseq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">관광명소</a></span>\r\n");
      out.write("          <span><a href=\"/planitshare/city/food.do?cseq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">음식점</a></span>\r\n");
      out.write("          <span><a href=\"/planitshare/city/plan.do?cseq=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("일정</a></span>\r\n");
      out.write("       	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("         <input type=\"hidden\" id=\"engname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.engname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\r\n");
      out.write("         \r\n");
      out.write("         <form method=\"POST\" action=\"/planitshare/citydetail.do\" >\r\n");
      out.write("         <div id=\"search-box\">\r\n");
      out.write("            <select class=\"form-control\">\r\n");
      out.write("               <option>음식점</option>\r\n");
      out.write("               <option>관광명소</option>\r\n");
      out.write("               <option>숙소</option>\r\n");
      out.write("            </select>\r\n");
      out.write("            <input type=\"text\" name=\"keyword\" id=\"\" class=\"form-control\" />\r\n");
      out.write("            <button class=\"btn btn-secondary\"><i class=\"fa-solid fa-magnifying-glass\"></i></button>\r\n");
      out.write("         </div>\r\n");
      out.write("         </form>\r\n");
      out.write("         \r\n");
      out.write("         <h2>오늘의 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 날씨</h2>\r\n");
      out.write("         <div class=\"weather\">\r\n");
      out.write("           <div class=\"iconinfo\">\r\n");
      out.write("           <div class=\"City\"></div>\r\n");
      out.write("            <div class=\"CurrIcon\" id=\"icon\"></div>\r\n");
      out.write("            <div class=\"CurrWeather\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"info\">\r\n");
      out.write("            <div class=\"CurrTemp\"></div>\r\n");
      out.write("            <div class=\"CurrWind\"></div>\r\n");
      out.write("            <div class=\"CurrHumi\"></div>\r\n");
      out.write("            <div class=\"CurrCloud\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("         </div>\r\n");
      out.write("         \r\n");
      out.write("         <h2 id=\"planhead\">인기 ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" 여행 일정</h2>\r\n");
      out.write("         <div id=\"list\">\r\n");
      out.write("          ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("        </div>\r\n");
      out.write("         \r\n");
      out.write("         \r\n");
      out.write("      </section>\r\n");
      out.write("   </main>\r\n");
      out.write("   \r\n");
      out.write("   <script>\r\n");
      out.write("   \r\n");
      out.write("   /* var engname = document.getElementById('engname').value;\r\n");
      out.write("   \r\n");
      out.write("   var apiURI = \"https://api.openweathermap.org/data/2.5/weather?q=\" + engname + \"&appid=9a588fe3b2d8a1189848d1b398ad0c77\";\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: apiURI,\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        type: \"GET\",\r\n");
      out.write("        async: \"false\",\r\n");
      out.write("        success: function(resp) {\r\n");
      out.write("           /* console.log(engname);\r\n");
      out.write("            console.log(resp);\r\n");
      out.write("            console.log(\"현재온도 : \"+ (resp.main.temp- 273.15) );\r\n");
      out.write("            console.log(\"현재습도 : \"+ resp.main.humidity);\r\n");
      out.write("            console.log(\"날씨 : \"+ resp.weather[0].main );\r\n");
      out.write("            console.log(\"상세날씨설명 : \"+ resp.weather[0].description );\r\n");
      out.write("            console.log(\"날씨 이미지 : \"+ resp.weather[0].icon );\r\n");
      out.write("            console.log(\"바람   : \"+ resp.wind.speed );\r\n");
      out.write("            console.log(\"나라   : \"+ resp.sys.country );\r\n");
      out.write("            console.log(\"도시이름  : \"+ resp.name );\r\n");
      out.write("            console.log(\"구름  : \"+ (resp.clouds.all) +\"%\" ); \r\n");
      out.write("            \r\n");
      out.write("            document.getElementById(\"temp\").innerHTML = (resp.main.temp- 273.15);\r\n");
      out.write("            document.getElementById(\"hum\").innerHTML = (resp.main.humidity);\r\n");
      out.write("            document.getElementById(\"weather\").innerHTML = (resp.weather[0].main);\r\n");
      out.write("            document.getElementById(\"disweather\").innerHTML = (resp.weather[0].description);\r\n");
      out.write("            document.getElementById(\"wind\").innerHTML = (resp.wind.speed);\r\n");
      out.write("            document.getElementById(\"country\").innerHTML = (resp.name);\r\n");
      out.write("            document.getElementById(\"cloud\").innerHTML = (resp.clouds.all) +\"%\";\r\n");
      out.write("            document.getElementById(\"image\").innerHTML = resp.weather[0].icon;\r\n");
      out.write("            \r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    }); */\r\n");
      out.write("    \r\n");
      out.write("    var engname = document.getElementById('engname').value;\r\n");
      out.write("    \r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        let weatherIcon = {\r\n");
      out.write("          '01' : 'fas fa-sun fa-5x',\r\n");
      out.write("          '02' : 'fas fa-cloud-sun fa-5x',\r\n");
      out.write("          '03' : 'fas fa-cloud fa-5x',\r\n");
      out.write("          '04' : 'fas fa-cloud-meatball fa-5x',\r\n");
      out.write("          '09' : 'fas fa-cloud-sun-rain fa-5x',\r\n");
      out.write("          '10' : 'fas fa-cloud-showers-heavy fa-5x',\r\n");
      out.write("          '11' : 'fas fa-poo-storm fa-5x',\r\n");
      out.write("          '13' : 'far fa-snowflake fa-5x',\r\n");
      out.write("          '50' : 'fas fa-smog fa-5x'\r\n");
      out.write("        };\r\n");
      out.write("\r\n");
      out.write("      $.ajax({\r\n");
      out.write("      url:'http://api.openweathermap.org/data/2.5/weather?q=' + engname + '&APPID=9a588fe3b2d8a1189848d1b398ad0c77&units=metric',\r\n");
      out.write("\r\n");
      out.write("      dataType:'json',\r\n");
      out.write("      type:'GET',\r\n");
      out.write("      success:function(data){\r\n");
      out.write("        var $Icon = (data.weather[0].icon).substr(0,2);\r\n");
      out.write("        var $Temp = '현재 온도: ' + Math.floor(data.main.temp) + 'º';\r\n");
      out.write("        var $city = data.name;\r\n");
      out.write("        var $wind = '현재 풍속: ' + data.wind.speed + 'm/s';\r\n");
      out.write("        var $humi = '현재 습도: ' + data.main.humidity + '%';\r\n");
      out.write("        var $cloud = '구름량: ' + data.clouds.all + '%';\r\n");
      out.write("        var $weather = data.weather[0].main;\r\n");
      out.write("\r\n");
      out.write("        $('.CurrIcon').append('<i class=\"' + weatherIcon[$Icon] +'\"></i>');\r\n");
      out.write("        $('.CurrTemp').prepend($Temp);\r\n");
      out.write("        $('.City').append($city);\r\n");
      out.write("        $('.CurrWind').append($wind);\r\n");
      out.write("        $('.CurrHumi').append($humi);\r\n");
      out.write("        $('.CurrCloud').append($cloud);\r\n");
      out.write("        $('.CurrWeather').append($weather);\r\n");
      out.write("        \r\n");
      out.write("        }\r\n");
      out.write("      })\r\n");
      out.write("      });\r\n");
      out.write("\r\n");
      out.write("   </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/inc/header.jsp(13,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	<div id=\"before-login\">\r\n");
          out.write("       <a href=\"/planitshare/login.do\">로그인</a>\r\n");
          out.write("       <a href=\"/planitshare/register.do\">회원가입</a>\r\n");
          out.write("  	 </div> \r\n");
          out.write("  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/inc/header.jsp(24,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty auth}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("   		<div id=\"login\">\r\n");
          out.write("		   \r\n");
          out.write("		   ");
          if (_jspx_meth_c_005fif_005f2(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		   \r\n");
          out.write("		    ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("		   \r\n");
          out.write("		 </div>\r\n");
          out.write("   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/inc/header.jsp(27,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${auth.loginmode eq 'user'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("		   <div id=\"header-profile\">\r\n");
          out.write("		       <div id=\"image-container\">\r\n");
          out.write("		       	   <div id=\"profile\"><img src=\"/planitshare/userimage/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${auth.profile}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" alt=\"\" ></div>\r\n");
          out.write("		       </div>\r\n");
          out.write("		       <div id=\"login-info\">\r\n");
          out.write("		       	   <div id=\"name\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${auth.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</div>	       	   \r\n");
          out.write("		           <div>\r\n");
          out.write("		               <a href=\"/planitshare/mypage.do\">마이페이지</a>\r\n");
          out.write("		               <a href=\"/planitshare/logout.do\">로그아웃</a>\r\n");
          out.write("		           </div>	           \r\n");
          out.write("		       </div>\r\n");
          out.write("		   </div>\r\n");
          out.write("		   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
      // /WEB-INF/views/inc/header.jsp(42,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${auth.loginmode eq 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("	           \r\n");
          out.write("		    <div id=\"header-profile\">\r\n");
          out.write("		       <div id=\"image-container\">\r\n");
          out.write("		       	   <div id=\"profile\"><img src=\"/planitshare/asset/image/admin.png\" alt=\"amdin-profile\" ></div>\r\n");
          out.write("		       </div>\r\n");
          out.write("		       <div id=\"login-info\">\r\n");
          out.write("		       	   <div id=\"name\">관리자님</div>\r\n");
          out.write("		       	    <div>\r\n");
          out.write("		               <a href=\"/planitshare/recommendcitylist.do\">관리자페이지</a>\r\n");
          out.write("		               <a href=\"/planitshare/logout.do\">로그아웃</a>\r\n");
          out.write("		           </div>\r\n");
          out.write("		       </div>\r\n");
          out.write("		   </div>\r\n");
          out.write("		    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/views/city/citydetail.jsp(196,10) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/city/citydetail.jsp(196,10) '${list}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${list}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/city/citydetail.jsp(196,10) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("dto");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("            <div class=\"planlist\" onclick=\"location.href='/planitshare/plan/view.do?seq=");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.seq}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("';\">\r\n");
            out.write("               <img src=\"/planitshare/asset/image/");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.image}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\">\r\n");
            out.write("               <div class=\"text\">\r\n");
            out.write("                   <div>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.title}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</div>\r\n");
            out.write("                   <span><i class=\"fa-solid fa-user\"></i>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.author}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                   <span><i class=\"fa-solid fa-eye\"></i>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.readCount}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                   <span><i class=\"fa-solid fa-heart\"></i>");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.likecnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</span>\r\n");
            out.write("                   ");
            if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("               </div>\r\n");
            out.write("            </div>\r\n");
            out.write("            ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/views/city/citydetail.jsp(204,19) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.reviewcnt > 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                   <span>(");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.reviewcnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write(")</span>\r\n");
          out.write("                   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }
}
